language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: required

before_install:
  - sudo apt-get update
  - sudo apt-get install nodejs
  - npm install -g npm@'>=1.4.3'

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - travis_retry composer setup
  - travis_retry npm install --no-bin-links
  - travis_retry bower install

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

script:
  - vendor/bin/phpunit
  - vendor/bin/behat