language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - npm install

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

before_script:
  - npm install npm -g
  - npm install
  - bower install

script:
  - vendor/bin/phpunit
  - vendor/bin/behat