language: php

php:
  - 5.5.9
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: required

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source
  - sudo apt-get update
  - sudo apt-get install nodejs
  - install npm
  - sudo npm install npm -g
  - sudo npm install --no-bin-links
  - bower install

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

script:
  - vendor/bin/phpunit
  - vendor/bin/behat